/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Highlight = {
  _id: string;
  _type: "highlight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ScheduleItem = {
  _id: string;
  _type: "scheduleItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  time?: string;
  live?: boolean;
};

export type Update = {
  _id: string;
  _type: "update";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HeroToggle = {
  _id: string;
  _type: "heroToggle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  useStreamingHero?: boolean;
  streamingChannel?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "streamingChannel";
  };
};

export type StreamingChannel = {
  _id: string;
  _type: "streamingChannel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  platform?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name?: string;
  streamUrl?: string;
  embedUrl?: string;
  description?: string;
  isActive?: boolean;
  isExternal?: boolean;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = Highlight | SanityImageCrop | SanityImageHotspot | ScheduleItem | Update | Sponsor | HeroToggle | StreamingChannel | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/queries/ChannelsListQuery.ts
// Variable: channelsListQuery
// Query: *[_type == "streamingChannel" && isActive == true ]| order(order asc){       _id,        platform,        name,        "logo": logo.asset->url,        streamUrl,        embedUrl,        isActive,        isExternal,        order           }
export type ChannelsListQueryResult = Array<{
  _id: string;
  platform: string | null;
  name: string | null;
  logo: string | null;
  streamUrl: string | null;
  embedUrl: string | null;
  isActive: boolean | null;
  isExternal: boolean | null;
  order: number | null;
}>;

// Source: ./src/lib/queries/highlightQuery.ts
// Variable: STATIC_HIGHLIGHT_SHAPE_QUERY
// Query: *[_type == "highlight"] {      _id,      title,      url,      "video": video.asset->url,      "thumbnail": thumbnail.asset->url    }
export type STATIC_HIGHLIGHT_SHAPE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  url: string | null;
  video: string | null;
  thumbnail: string | null;
}>;

// Source: ./src/lib/queries/scheduleQuery.ts
// Variable: scheduleQuery
// Query: *[_type == "scheduleItem"] | order(time asc) {      _id,      title,      time,      "imageUrl": image.asset->url,      live    }
export type ScheduleQueryResult = Array<{
  _id: string;
  title: string | null;
  time: string | null;
  imageUrl: null;
  live: boolean | null;
}>;

// Source: ./src/lib/queries/sponsorQuery.ts
// Variable: sponsorsQuery
// Query: *[_type == "sponsor"]{        _id,        title,        "imageUrl": image.asset->url      }
export type SponsorsQueryResult = Array<{
  _id: string;
  title: string | null;
  imageUrl: string | null;
}>;

// Source: ./src/lib/queries/streaming-hro-query.ts
// Variable: streamingHeroQuery
// Query: *[_type == "heroToggle"][0]{      _id,      useStreamingHero,      streamingChannel->{        _id,        platform,        name,        "logo": logo.asset->url,        streamUrl,        embedUrl,        isActive,        isExternal,        order         }    }
export type StreamingHeroQueryResult = {
  _id: string;
  useStreamingHero: boolean | null;
  streamingChannel: {
    _id: string;
    platform: string | null;
    name: string | null;
    logo: string | null;
    streamUrl: string | null;
    embedUrl: string | null;
    isActive: boolean | null;
    isExternal: boolean | null;
    order: number | null;
  } | null;
} | null;

// Source: ./src/lib/queries/updateQuery.ts
// Variable: updatesQuery
// Query: *[_type == "update"] | order(_createdAt desc){      _id,      title,      "imageUrl": image.asset->url,      _createdAt    }
export type UpdatesQueryResult = Array<{
  _id: string;
  title: string | null;
  imageUrl: string | null;
  _createdAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"streamingChannel\" && isActive == true ]| order(order asc){\n       _id,\n        platform,\n        name,\n        \"logo\": logo.asset->url,\n        streamUrl,\n        embedUrl,\n        isActive,\n        isExternal,\n        order   \n        }": ChannelsListQueryResult;
    "\n    *[_type == \"highlight\"] {\n      _id,\n      title,\n      url,\n      \"video\": video.asset->url,\n      \"thumbnail\": thumbnail.asset->url\n    }\n  ": STATIC_HIGHLIGHT_SHAPE_QUERYResult;
    "\n    *[_type == \"scheduleItem\"] | order(time asc) {\n      _id,\n      title,\n      time,\n      \"imageUrl\": image.asset->url,\n      live\n    }\n  ": ScheduleQueryResult;
    "*[_type == \"sponsor\"]{\n        _id,\n        title,\n        \"imageUrl\": image.asset->url\n      }": SponsorsQueryResult;
    "\n    *[_type == \"heroToggle\"][0]{\n      _id,\n      useStreamingHero,\n      streamingChannel->{\n        _id,\n        platform,\n        name,\n        \"logo\": logo.asset->url,\n        streamUrl,\n        embedUrl,\n        isActive,\n        isExternal,\n        order   \n      }\n    }\n  ": StreamingHeroQueryResult;
    "\n    *[_type == \"update\"] | order(_createdAt desc){\n      _id,\n      title,\n      \"imageUrl\": image.asset->url,\n      _createdAt\n    }\n  ": UpdatesQueryResult;
  }
}
